# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1806ae15614a9db9dc5237152dea87f239a89205d1b79a69a0a0a6aff365e6b4ff10b6bb5035a299d490d9f4e888a247f4937956885b0363aa5f9e2ed6c72a

test:
  secret_key_base: 9a8a72640b6cd31e80a69b5d0e9b6c714134a98b074844f10e3e1489dac9a8d84e0bcd95f6573d4201302476c1d6568bf399fc7f7ab693d91a746fc073948369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
